---
deployment:
  tasks:
    - echo "Starting deployment for Node.js application..."
    - export DEPLOY_PATH=/home/zipbuyin/Active/GSB_Company
    - echo "Deploying to $DEPLOY_PATH"
    - mkdir -p $DEPLOY_PATH
    - rsync -av --exclude='.git' --exclude='node_modules' . $DEPLOY_PATH/
    - cd $DEPLOY_PATH
    - echo "Installing dependencies..."
    - npm install --production
    - echo "Restarting application..."
    - npx pm2 start app.js --name "nodeapp" --watch
    - echo "Deployment completed!"
